let token=localStorage.getItem('dmrToken')||'';let me=null,settings={};
const app=document.getElementById('app'),nav=document.getElementById('nav');
async function api(url,opt={}){opt.headers=Object.assign({'Content-Type':'application/json'},opt.headers||{});if(token)opt.headers.Authorization='Bearer '+token;const r=await fetch(url,opt);const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed');return d}
function button(label,fn){const b=document.createElement('button');b.textContent=label;b.onclick=fn;return b}
function renderNav(){nav.innerHTML='';nav.append(button('Home',()=>show('home')));nav.append(button('Papers',()=>show('papers')));nav.append(button('Ranking',()=>show('ranking')));nav.append(button('Announcements',()=>show('ann')));if(me)nav.append(button('Dashboard',()=>show('dashboard')));if(me?.role==='admin')nav.append(button('Admin',()=>show('admin')));nav.append(button(me?'Logout':'Login',me?logout:()=>show('login')))}
function wrap(title,html){app.innerHTML=`<div class="wrap"><h1>${title}</h1>${html}</div>`}
async function show(page){try{
 if(page==='home'){const ss=await api('/api/subjects');wrap('DMR',`<section class="hero"><h1>${settings.site_name}</h1><p>${settings.tagline}</p><button class="primary" id="browse">Browse Papers</button></section><h2>Subjects</h2><div class="grid">${ss.map(s=>`<div class="card"><h3>${s.name}</h3><p class="muted">A/L learning</p></div>`).join('')}</div>`);document.getElementById('browse').onclick=()=>show('papers')}
 if(page==='login'){wrap('Login',`<div class="card" style="max-width:430px"><label>Username</label><input id="lu"><label>Password</label><input id="lp" type="password"><button class="primary" id="loginButton">Login</button><p id="loginMsg"></p></div>`);document.getElementById('loginButton').addEventListener('click',login)}
 if(page==='papers'){const ps=await api('/api/papers');wrap('Papers',`<div class="grid">${ps.length?ps.map(p=>`<div class="card"><b>${p.subject}</b><h3>${p.title}</h3><p>${p.year} ${p.term}</p><p>Total marks: ${p.total_marks}</p></div>`).join(''):'<p>No papers published yet.</p>'}</div>`)}
 if(page==='ranking'){if(!me){wrap('Ranking','<div class="card">Please login to view rankings.</div>');return}const r=await api('/api/rankings');wrap('Rankings',`<div class="card"><table><tr><th>Rank</th><th>Name</th><th>District</th><th>School</th><th>Class</th><th>Total</th></tr>${r.map(x=>`<tr><td>${x.rank}</td><td>${x.name}</td><td>${x.district||'-'}</td><td>${x.school||'-'}</td><td>${x.class_name||'-'}</td><td>${x.score}</td></tr>`).join('')}</table></div>`)}
 if(page==='ann'){const a=await api('/api/announcements');wrap('Announcements',a.map(x=>`<div class="card"><h3>${x.title}</h3><p>${x.body}</p><small>${x.created_at}</small></div>`).join('')||'<p>No announcements.</p>')}
 if(page==='dashboard'){if(!me){show('login');return}const m=await api('/api/marks');wrap('Student Dashboard',`<div class="grid"><div class="card"><h2>${m.length}</h2><p>Papers marked</p></div><div class="card"><h2>${m.reduce((a,x)=>a+Number(x.score),0)}</h2><p>Total marks</p></div></div><div class="card"><h2>My Results</h2><table><tr><th>Paper</th><th>Subject</th><th>Score</th><th>Feedback</th></tr>${m.map(x=>`<tr><td>${x.paper}</td><td>${x.subject}</td><td>${x.score}/${x.total_marks}</td><td>${x.feedback||'-'}</td></tr>`).join('')}</table></div>`)}
 if(page==='admin'){if(me?.role!=='admin'){show('login');return}await adminPage()}
 }catch(e){wrap('Error',`<p class="error">${e.message}</p>`)}}
async function login(){try{const d=await api('/api/login',{method:'POST',body:JSON.stringify({username:document.getElementById('lu').value,password:document.getElementById('lp').value})});token=d.token;me=d.user;localStorage.setItem('dmrToken',token);renderNav();show('admin')}catch(e){document.getElementById('loginMsg').textContent=e.message;document.getElementById('loginMsg').className='error'}}
function logout(){token='';me=null;localStorage.removeItem('dmrToken');renderNav();show('home')}
async function adminPage(){const [u,p,s,m]=await Promise.all([api('/api/users'),api('/api/papers'),api('/api/subjects'),api('/api/marks')]);wrap('Admin Control Center',`<div class="grid"><div class="card"><h2>Add Student</h2><input id="su" placeholder="Username"><input id="sp" placeholder="Password"><input id="sn" placeholder="Name"><input id="sd" placeholder="District"><input id="ss" placeholder="School"><input id="sc" placeholder="Class"><button class="primary" id="addS">Create Student</button></div><div class="card"><h2>Add Paper</h2><input id="pt" placeholder="Paper title"><select id="ps">${s.map(x=>`<option value="${x.id}">${x.name}</option>`).join('')}</select><input id="py" placeholder="Year"><input id="ptm" placeholder="Term"><input id="pm" type="number" value="100"><button class="primary" id="addP">Publish Paper</button></div><div class="card"><h2>Enter Marks</h2><select id="mp">${p.map(x=>`<option value="${x.id}">${x.title}</option>`).join('')}</select><select id="mu">${u.map(x=>`<option value="${x.id}">${x.name}</option>`).join('')}</select><input id="mv" type="number" placeholder="Score"><input id="mf" placeholder="Feedback"><button class="primary" id="addM">Save Marks</button></div><div class="card"><h2>Announcement</h2><input id="at" placeholder="Title"><textarea id="ab" placeholder="Message"></textarea><button class="primary" id="addA">Publish</button></div></div><div class="card"><h2>Website Settings</h2><input id="site" value="${settings.site_name}"><input id="tag" value="${settings.tagline}"><button class="primary" id="saveSet">Save Settings</button></div><div class="card"><h2>Students</h2><table><tr><th>Name</th><th>Username</th><th>District</th><th>School</th><th>Class</th></tr>${u.map(x=>`<tr><td>${x.name}</td><td>${x.username}</td><td>${x.district}</td><td>${x.school}</td><td>${x.class_name}</td></tr>`).join('')}</table></div>`);
document.getElementById('addS').onclick=async()=>{await api('/api/users',{method:'POST',body:JSON.stringify({username:su.value,password:sp.value,name:sn.value,district:sd.value,school:ss.value,class_name:sc.value})});adminPage()};document.getElementById('addP').onclick=async()=>{await api('/api/papers',{method:'POST',body:JSON.stringify({title:pt.value,subject_id:ps.value,year:py.value,term:ptm.value,total_marks:pm.value})});adminPage()};document.getElementById('addM').onclick=async()=>{await api('/api/marks',{method:'POST',body:JSON.stringify({paper_id:mp.value,student_id:mu.value,score:mv.value,feedback:mf.value})});adminPage()};document.getElementById('addA').onclick=async()=>{await api('/api/announcements',{method:'POST',body:JSON.stringify({title:at.value,body:ab.value})});adminPage()};document.getElementById('saveSet').onclick=async()=>{settings=await api('/api/settings',{method:'PUT',body:JSON.stringify({site_name:site.value,tagline:tag.value})});document.getElementById('siteName').textContent=settings.site_name;document.getElementById('tagline').textContent=settings.tagline;adminPage()}}
async function init(){settings=await api('/api/settings');document.getElementById('siteName').textContent=settings.site_name;document.getElementById('tagline').textContent=settings.tagline;if(token){try{me=await api('/api/me')}catch{token='';localStorage.removeItem('dmrToken');me=null}}renderNav();show('home')}
init();
